name: "CMT3A-MSS"
exclude: [ "LICENSE", "README.md", "assignments", "resources"]
navbar:
  title: "CMT3A-MSS"
  type: default
  left:
    - text: ""
      href: index.html
      icon: fa-home fa-lg
    - text: "Schedule"
      href: schedule.html
      icon: fa-tasks fa-lg
    - text: "Challenges"
      href: challenges.html
      icon: fa-chess fa-lg
    - text: "Project"
      href: project.html
      icon: fa-file-code fa-lg
    - text: "Onboarding"
      href: onboarding.html
      icon: fa-award fa-lg
    - text: "Resources"
      href: resources.html
      icon: fa-toolbox fa-lg
  right:
    - icon: fa-github fa-lg
      href: https://github.com/mickaeltemporao/CMT3A-MSS
output_dir: "docs"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    include:
      after_body: footer.html
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: true
    html5: true

